apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: apbpa0ygh-nodejs 
  janus-idp.io/tekton: apbpa0ygh-nodejs
  backstage.io/kubernetes-id: apbpa0ygh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: apbpa0ygh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  