apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: apbpa0ygh-nodejs
  janus-idp.io/tekton: apbpa0ygh-nodejs
  backstage.io/kubernetes-id: apbpa0ygh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: apbpa0ygh-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
