apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: apbpa0ygh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apbpa0ygh-nodejs 
  name: apbpa0ygh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: apbpa0ygh-nodejs 
